### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by skinnyzaz** [ghomasHudson/Jellyfin-Auto-Collections#15]
config is setup for   imdb_chart_ids = ["moviemeter"]
When I run imdb_chart.py I get the following.

```
Getting collections list...


Traceback (most recent call last):
  File "/opt/Jellyfin-Auto-Collections/imdb_chart.py", line 36, in <module>
    list_name = html.unescape(res.text.split('<h1 class="header">')[1].split("</h1>")[0])
IndexError: list index out of range
```

**Comment by ghomasHudson** [comment]
Just confirmed that on my version - will investigate.

**Comment by skinnyzaz** [comment]
I am available for any testing needed.

**Comment by skinnyzaz** [comment]
Just tested this again hoping it would work but sadly its still broken :(

**Comment by ghomasHudson** [comment]
> Just tested this again hoping it would work but sadly its still broken :(

Have done a complete rewrite of this repo to make things a lot more modular and robust. This should fix your issue. Let me know if not.
