### ISSUE TITLE
Support for mdblist.com

### ISSUE THREAD

**Issue by titooo7** [ghomasHudson/Jellyfin-Auto-Collections#18]
mdblist can be very easy to read if you add /json to the url of the list. For instance: https://[mdblist.com/lists/garycrawfordgc/top-movies-of-the-week/json/](https://mdblist.com/lists/garycrawfordgc/top-movies-of-the-week/json/)

those urls contain the imdb id and movie titles, so I´m hoping it´d be easier for you to create a script to support that site as well :)

**Comment by ghomasHudson** [comment]
Started work on this: https://github.com/ghomasHudson/Jellyfin-Auto-Collections/tree/rewrite

**Comment by ghomasHudson** [comment]
Done!
