### ISSUE TITLE
trakt

### ISSUE THREAD

**Issue by Yankees4life** [ghomasHudson/Jellyfin-Auto-Collections#19]
Any plans to add trakt integration? That would be nice to have on hand. I've been trying to put together a script myself for it but no avail. 

Cheers

**Comment by Yankees4life** [comment]
@ghomasHudson could you merge the PR pls? I'm sure others would like to use this too

**Comment by ghomasHudson** [comment]
This should be integrated now. It requires a little setup, creating client_secrets and ids, authenticating etc.
