### ISSUE TITLE
Shows?

### ISSUE THREAD

**Issue by Yankees4life** [ghomasHudson/Jellyfin-Auto-Collections#2]
Hello there

I love using your tool to create curated collections but I find that it only works for movies. Any plans to integrate shows as well to this as I have some lists that I want to curate for them.

Cheers

**Comment by ghomasHudson** [comment]
This one will take a little more time as I need to think about how to match the start and end dates. Should be possible though.

**Comment by Yankees4life** [comment]
> This one will take a little more time as I need to think about how to match the start and end dates. Should be possible though.

To be honest, you could just let the tool just point to the folder instead of trying to track all of the episodes. I find using nested collections (ie basically making a collection point to a show folder) makes it a bit easy to implement. 

With movies, you only got the movie to worry about but with shows, there's episodes so just pointing to the folder will work IMO

**Comment by Yankees4life** [comment]
I just figured it out myself on how to do it. Gonna need to make a separate file for the shows. Will push a PR and you could take a look

**Comment by Yankees4life** [comment]
And...done
https://github.com/ghomasHudson/Jellyfin-Auto-Collections/pull/8
