### ISSUE TITLE
add_tcm_intro.py

### ISSUE THREAD

**Issue by p37307** [ghomasHudson/Jellyfin-Auto-Collections#22]
FYI, In the package, to add Turner Classic movies intros and outros to your movies as extras, the file is **_add_tcm.py_** but in your README document https://github.com/ghomasHudson/Jellyfin-Auto-Collections/blob/master/README.md, you call for _**add_tcm_intro.py**_.

**Comment by ghomasHudson** [comment]
> FYI, In the package, to add Turner Classic movies intros and outros to your movies as extras, the file is **_add_tcm.py_** but in your README document https://github.com/ghomasHudson/Jellyfin-Auto-Collections/blob/master/README.md, you call for _**add_tcm_intro.py**_.

Thanks for the heads up - I've moved the intros functionality into a separate repo: https://github.com/ghomasHudson/Jellyfin-Movie-Intros
