### ISSUE TITLE
10.9.0+ breaks functionality 

### ISSUE THREAD

**Issue by slimshizn** [ghomasHudson/Jellyfin-Auto-Collections#23]
Traceback while running letterboxd_list.py. (running prior to update without issue.)

```
Traceback (most recent call last):
  File "/opt/jellyfin/Jellyfin-Auto-Collections/letterboxd_list.py", line 82, in <module>
    update_letterboxd_list_collections(app_config)
  File "/opt/jellyfin/Jellyfin-Auto-Collections/letterboxd_list.py", line 53, in update_letterboxd_list_collections
    collection_data = get_collection_data_from_letterboxd_list(list_id)
  File "/opt/jellyfin/Jellyfin-Auto-Collections/letterboxd_list.py", line 20, in get_collection_data_from_letterboxd_list
    list_name = html.unescape(res.text.split('<h1 class="title-1 prettify">')[1].split("</h1>")[0]).strip()
IndexError: list index out of range
```

**Comment by BoHoliday** [comment]
Any update on this? Functionality is still broken on 10.9+

**Comment by mzrimsek** [comment]
Just out of curiosity have you tried running stuff through the Docker container? I just ran that against my Jellyfin instance and it worked.

**Comment by ghomasHudson** [comment]
@slimshizn That error looks like it's nothing to do with the jellyfin server version - it's an error parsing the letterbox list page - Are you sure your letterbox list ids in `config.yaml` are correct?

If this doesn't fix things post your `config.yaml` here and I'll do some investigation. It seems to work fine for me on 10.9.3.

**Comment by mzrimsek** [comment]
> @slimshizn That error looks like it's nothing to do with the jellyfin server version - it's an error parsing the letterbox list page - Are you sure your letterbox list ids in `config.yaml` are correct?
> 
> If this doesn't fix things, post your `config.yaml` here and I'll do some investigation. It seems to work fine for me on 10.9.3.

This was my next thought is the config changed a bit with the update and the script is failing to pick it up.

**Comment by ghomasHudson** [comment]
Very True. This repo is just a random collection of scripts I wrote for myself. It's not even properly parsing the html of the list pages.

I'll do a bit of a rewrite tonight.

**Comment by BoHoliday** [comment]
Thanks for the replies! I use the Trakt version and was going to try to fix it, but I admittedly don't know much about how this works.

**Comment by ghomasHudson** [comment]
I've done a rewrite of everything which uses a plugin architecture to make things a lot more maintainable - https://github.com/ghomasHudson/Jellyfin-Auto-Collections/tree/rewrite

Just need to add back in all the config option, docker container etc and will push to main.
