### ISSUE TITLE
Top 250??

### ISSUE THREAD

**Issue by Yankees4life** [ghomasHudson/Jellyfin-Auto-Collections#3]
Any plans to add top 250 lists to the lists of tools to curate collections? I can curate custom made imdb lists but I can't get the top250 charts working 
https://m.imdb.com/chart/top/

**Comment by ghomasHudson** [comment]
Thanks for pointing this out - should be a relatively quick fix - will look tonight.

**Comment by ghomasHudson** [comment]
Have added `imdb_chart.py` which should do this (split them into two files because the pages are substantially different.

Let me know if it works.

**Comment by Yankees4life** [comment]
Yep. That worked
