### ISSUE TITLE
Match by External IDs

### ISSUE THREAD

**Issue by ghomasHudson** [ghomasHudson/Jellyfin-Auto-Collections#31]
Jellyfin items may have the IMDb or tmdb ids as metadata. We should search by these first for higher quality matching than name + year (which we can fallback to if no items are found with the id).

**Comment by BoHoliday** [comment]
This would be great since the plugin doesn't work properly for show-only lists. Currently, the plugin adds random episodes with the same name from other shows and sometimes even adds movies to the collection when it's supposed to only be searching for shows.

**Comment by ghomasHudson** [comment]
Added a partial implementation - imdb ids are now used as an additional filter. Searching via imdb_id doesnt seem to be supported by the jellyfin api so I'll have to work on the implementation.

**Comment by BoHoliday** [comment]
> Added a partial implementation - imdb ids are now used as an additional filter. Searching via imdb_id doesnt seem to be supported by the jellyfin api so I'll have to work on the implementation.

This is great! Thanks so much for the work. Will this be implemented into the mdblist plugin as well?

**Comment by ghomasHudson** [comment]
is it not working already?

**Comment by ghomasHudson** [comment]
> The mdblist plugin is still adding single episodes or movies to the collection with the same name instead of the _series_, so I don't think it's using any imdb ids as a filter. I have series-only collections, and the script doesn't seem to know that it should only be adding _series_ to the collection, not episodes or movies.

Well. There are 2 problems here. The existing implementation fell back to basic matches if there was no imdb_match. I've fixed this so if `imdb_id` is present, it will only match with imdb ids.

Secondly, the media type filters in [jellyfin.py
](https://github.com/BoHoliday/Jellyfin-Auto-Collections/blob/46868511321398fd6c975838ea501c88667ba2a6/utils/jellyfin.py#L8-L17) need updating. I'll push some changes to hopefully fix these issues.

**Comment by BoHoliday** [comment]
> > The mdblist plugin is still adding single episodes or movies to the collection with the same name instead of the _series_, so I don't think it's using any imdb ids as a filter. I have series-only collections, and the script doesn't seem to know that it should only be adding _series_ to the collection, not episodes or movies.
> 
> Well. There are 2 problems here. The existing implementation fell back to basic matches if there was no imdb_match. I've fixed this so if `imdb_id` is present, it will only match with imdb ids.
> 
> Secondly, the media type filters in [jellyfin.py ](https://github.com/BoHoliday/Jellyfin-Auto-Collections/blob/46868511321398fd6c975838ea501c88667ba2a6/utils/jellyfin.py#L8-L17) need updating. I'll push some changes to hopefully fix these issues.

Works flawlessly now, thank you!
