### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

### ISSUE THREAD

**Issue by Druidblack** [ghomasHudson/Jellyfin-Auto-Collections#41]
![1](https://github.com/ghomasHudson/Jellyfin-Auto-Collections/assets/70659424/ee1ac903-22ca-40aa-b371-3a77933c2019)
![2](https://github.com/ghomasHudson/Jellyfin-Auto-Collections/assets/70659424/f3c2b944-891d-4894-a751-334d367b2e01)
![3](https://github.com/ghomasHudson/Jellyfin-Auto-Collections/assets/70659424/e7524af9-d39a-4664-b520-443ef8e87585)
![4](https://github.com/ghomasHudson/Jellyfin-Auto-Collections/assets/70659424/6e81e759-a555-4e6f-bcad-6b9eeb0b2e24)

Good afternoon. I seem to be doing everything as always. But the program does not see the configuration file in the directory. What am I doing wrong?

**Comment by ghomasHudson** [comment]
You're doing nothing wrong - the config path wasn't specified correctly in the Dockerfile. I've updated the repo which should now fix the problem.

**Comment by Druidblack** [comment]
I updated the docker image, but the problem with the configuration file remained.

**Comment by Druidblack** [comment]
Thank you. Everything is working now. 

I have two more questions about work

1. Are the covers for the collection not loading? or am I having problems with pictures for collections?

2. Apparently there is some kind of problem with adding TV series. I have 1300 TV series in my library and not one of them was not included in the collections created by your plugins.

**Comment by ghomasHudson** [comment]
> Thank you. Everything is working now.
> 
> I have two more questions about work
> 
>     1. Are the covers for the collection not loading? or am I having problems with pictures for collections?

This script doesn't currently add covers to the collections it makes (See #33 ). You can of course add your own manually in jellyfin for now.

>     2. Apparently there is some kind of problem with adding TV series. I have 1300 TV series in my library and not one of them was not included in the collections created by your plugins.

Can you open a new issue with the specific lists you're using?

**Comment by darkneo86** [comment]
I'm having this exact same issue, actually. running the latest version of your repo. I've been beating my head - it was working yesterday, just not doing what I wanted. And now, today, I'm having that error. Even forcing recreate and such of my docker. Any ideas? Sorry to reopen this ticket. I can switch to my server if pictures or logs are needed, but it's pretty much the same issue.
