### ISSUE TITLE
There is no data for the list of Best TV episodes of all time

### ISSUE THREAD

**Issue by Druidblack** [ghomasHudson/Jellyfin-Auto-Collections#44]
There is no data for the list of Best TV episodes of all time
![Безымянный](https://github.com/ghomasHudson/Jellyfin-Auto-Collections/assets/70659424/c4e10210-f24e-441a-8315-9f485b0165bc)

**Comment by ghomasHudson** [comment]
What's the list you're adding? (is it letterboxd, imdb, etc? what's the list id?)

**Comment by Druidblack** [comment]
imdb_list, ls087301829

**Comment by ghomasHudson** [comment]
Ah this is a list of TV **episodes** not shows which hasn't really been tested fully yet with imdb.
