### ISSUE TITLE
error when getting box office from imdb

### ISSUE THREAD

**Issue by vortex91** [ghomasHudson/Jellyfin-Auto-Collections#6]
set config for boxoffice and run

Getting collections list...

found Top Box Office (US) fbfa3ded28e452ac0d9df5d567b66776
************************************************

Traceback (most recent call last):
~/Jellyfin-Auto-Collections-master/imdb_chart.py", line 41, in <module>
    text = res.text.split('<tbody class="lister-list">', 1)[1]
IndexError: list index out of range

**Comment by ghomasHudson** [comment]
Should be fixed now so closing - let me know if you have any more problems.
