### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by ghomasHudson** [ghomasHudson/Jellyfin-Auto-Collections#7]
Wrap things up in a docker container that runs the scripts on a schedule.

**Comment by mzrimsek** [comment]
I forked this project and have a Dockerized version running with scheduling. I did rework quite a bit in terms of how stuff is configured but have it documented decently I think. I plan to let it run for a few days to make sure it's all good and then I can throw up a PR if you'd like.

**Comment by ghomasHudson** [comment]
Perfect - looks really good!

**Comment by mzrimsek** [comment]
I threw up the PR after it seems to be working well. Lmk if you want to share some of the ideas you have for enhancing things...I may have some time to help out. I really just wanted to make a collection from the movie nights I take part in for a streamer I watch and it was way too many movies to do manually so I've added what I want to get that stuff working but I am open to helping out some more. Working on this was a very fun couple day project.
