### ISSUE TITLE
imdb lists with more than 100 movies

### ISSUE THREAD

**Issue by dt2i** [ghomasHudson/Jellyfin-Auto-Collections#9]
This only grabs the first 100 movies in any imdb list

**Comment by ghomasHudson** [comment]
Do you have an example of a long imdb list we can test with?

**Comment by dt2i** [comment]
confirmed that this is fixed

**Comment by mikewesten** [comment]
@ghomasHudson This appears to still be an issue with the Letterboxd lists. After 100 items the scan is stopped. This may be an issue with other scipts as well but so far I've only really tested out the Letterboxd script.
